# Generated by Django 2.2.6 on 2019-10-29 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('residence', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=150, null=True)),
                ('occupation', models.CharField(max_length=150, null=True)),
                ('marital_status', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField()),
                ('recorded_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('usn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('pid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('attendance', models.IntegerField(default=0)),
                ('subcode', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subcode', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.teacher')),
                ('usn', models.ManyToManyField(null=True, to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atten', models.IntegerField(default=0)),
                ('subcode1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.subjects')),
                ('usn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
    ]
