# Generated by Django 2.2.6 on 2019-10-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20191029_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendances',
            old_name='atten',
            new_name='attendance',
        ),
    ]
