# Generated by Django 2.2.6 on 2019-10-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20191029_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
