# Generated by Django 2.2.6 on 2019-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_delete_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pid',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
