# Generated by Django 2.2.6 on 2019-11-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20191114_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
